{"name": "validate user is able to login with Valid Credentials -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55bf51e3675a <unknown>\n#1 0x55bf518e94b0 <unknown>\n#2 0x55bf5193a9b3 <unknown>\n#3 0x55bf5193aba1 <unknown>\n#4 0x55bf519891f4 <unknown>\n#5 0x55bf519605bd <unknown>\n#6 0x55bf519865e0 <unknown>\n#7 0x55bf51960363 <unknown>\n#8 0x55bf5192cd63 <unknown>\n#9 0x55bf5192d9c1 <unknown>\n#10 0x55bf51dfba6b <unknown>\n#11 0x55bf51dff951 <unknown>\n#12 0x55bf51de3b62 <unknown>\n#13 0x55bf51e004c4 <unknown>\n#14 0x55bf51dc813f <unknown>\n#15 0x55bf51e246f8 <unknown>\n#16 0x55bf51e248d6 <unknown>\n#17 0x55bf51e355a6 <unknown>\n#18 0x7f97f771c609 start_thread\n\n", "trace": "  File \"/home/thriveni/Assignment/practiceAutomation/.venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/thriveni/Assignment/practiceAutomation/.venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"behave_test_cases/steps/login_steps.py\", line 36, in step_impl\n    context.myAcc.verify_user_logged_in_successfully(UserName)\n  File \"/home/thriveni/Assignment/practiceAutomation/pages/myAccount_page.py\", line 45, in verify_user_logged_in_successfully\n    self.wait_for_element(locator_type=\"xpath\", locator_value=\"//div[@class='woocommerce-MyAccount-content']\",\n  File \"/home/thriveni/Assignment/practiceAutomation/base/basepage.py\", line 25, in wait_for_element\n    element= wait.until(EC.visibility_of_element_located((locator_type,locator_value)))\n  File \"/home/thriveni/Assignment/practiceAutomation/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given user is on home screen page", "status": "passed", "start": 1747377485700, "stop": 1747377489375}, {"name": "When user clicks on My Account menu", "status": "passed", "start": 1747377489375, "stop": 1747377490922}, {"name": "And enters registered \"map\" and valid \"Kanasu!5\"", "status": "passed", "start": 1747377490922, "stop": 1747377491299}, {"name": "And clicks on the login button", "status": "passed", "start": 1747377491299, "stop": 1747377492525}, {"name": "Then User(\"map\") should successfully login to the web page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55bf51e3675a <unknown>\n#1 0x55bf518e94b0 <unknown>\n#2 0x55bf5193a9b3 <unknown>\n#3 0x55bf5193aba1 <unknown>\n#4 0x55bf519891f4 <unknown>\n#5 0x55bf519605bd <unknown>\n#6 0x55bf519865e0 <unknown>\n#7 0x55bf51960363 <unknown>\n#8 0x55bf5192cd63 <unknown>\n#9 0x55bf5192d9c1 <unknown>\n#10 0x55bf51dfba6b <unknown>\n#11 0x55bf51dff951 <unknown>\n#12 0x55bf51de3b62 <unknown>\n#13 0x55bf51e004c4 <unknown>\n#14 0x55bf51dc813f <unknown>\n#15 0x55bf51e246f8 <unknown>\n#16 0x55bf51e248d6 <unknown>\n#17 0x55bf51e355a6 <unknown>\n#18 0x7f97f771c609 start_thread\n\n", "trace": "  File \"/home/thriveni/Assignment/practiceAutomation/.venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/thriveni/Assignment/practiceAutomation/.venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"behave_test_cases/steps/login_steps.py\", line 36, in step_impl\n    context.myAcc.verify_user_logged_in_successfully(UserName)\n  File \"/home/thriveni/Assignment/practiceAutomation/pages/myAccount_page.py\", line 45, in verify_user_logged_in_successfully\n    self.wait_for_element(locator_type=\"xpath\", locator_value=\"//div[@class='woocommerce-MyAccount-content']\",\n  File \"/home/thriveni/Assignment/practiceAutomation/base/basepage.py\", line 25, in wait_for_element\n    element= wait.until(EC.visibility_of_element_located((locator_type,locator_value)))\n  File \"/home/thriveni/Assignment/practiceAutomation/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1747377492526, "stop": 1747377497610}], "attachments": [{"name": "Screenshot", "source": "ea7fe5bb-f940-4c91-83f3-fd08d21a4595-attachment.png", "type": "image/png"}], "parameters": [{"name": "UserName", "value": "map"}, {"name": "Password", "value": "Kanasu!5"}], "start": 1747377485678, "stop": 1747377502772, "uuid": "c19cbc89-ca24-40d8-85b2-2cb1eb075445", "historyId": "5ef36b143516be16bd431707d7be77bf", "fullName": "Login to Automation Practice Site: validate user is able to login with Valid Credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "positivenew"}, {"name": "feature", "value": "Login to Automation Practice Site"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}